# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
   config.vm.network "private_network", type: "dhcp"

   config.vm.define "minecraft" do |minecraft|
      minecraft.vm.box = "geerlingguy/ubuntu1604"
      minecraft.vm.network :private_network, ip: "172.24.48.55"
      minecraft.vm.provision "chef_solo" do |chef|
          chef.cookbooks_path = "../chef-repo/cookbooks"
          chef.roles_path = "../chef-repo/roles"
          chef.add_role("minecraft")
      end
     minecraft.vm.network "forwarded_port", guest: 80, host: 8080
  end
  
end
